# Generated by Django 2.2.7 on 2019-11-21 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=500)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('gp', '股票'), ('zq', '债券'), ('jj', '基金')], default='gp', max_length=10)),
                ('algo_content', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_capital', models.CharField(db_index=True, max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article', to=settings.AUTH_USER_MODEL)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_column', to='article.ArticleColumn')),
            ],
            options={
                'ordering': ('-updated',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
