# Generated by Django 2.2.7 on 2019-11-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_algorithmpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithmpost',
            old_name='algo_content',
            new_name='body',
        ),
    ]
