# Generated by Django 2.2.7 on 2019-11-21 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20191121_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algorithmpost',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='algorithmpost',
            name='initial_capital',
        ),
        migrations.RemoveField(
            model_name='algorithmpost',
            name='start_date',
        ),
    ]
