# Generated by Django 2.2.7 on 2019-11-23 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_algocolumn_myalgopost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algocolumn',
            name='user',
        ),
    ]
