# Generated by Django 2.2.7 on 2019-11-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_remove_algocolumn_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myalgopost',
            name='initial_capital',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
