# Generated by Django 2.2.7 on 2019-11-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20191123_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='myalgopost',
            name='target_return',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
