# Generated by Django 2.2.8 on 2019-12-09 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0012_myalgopost_algo_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myalgopost',
            name='column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algo_type_column', to='article.AlgoColumn'),
        ),
    ]
