# Generated by Django 2.2.8 on 2019-12-09 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0014_auto_20191209_1945'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgoOpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config', models.TextField(blank=True)),
                ('algopost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algopost', to='article.MyalgoPost')),
            ],
        ),
    ]
