# Generated by Django 2.2.8 on 2019-12-09 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_algoopt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algoopt',
            name='algopost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='algopost', to=settings.AUTH_USER_MODEL),
        ),
    ]
