# Generated by Django 2.2.8 on 2019-12-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20191209_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoopt',
            name='task_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='algorithmpost',
            name='title',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
