# Generated by Django 2.2.8 on 2019-12-09 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_auto_20191209_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algoopt',
            name='task_name',
        ),
    ]
