# Generated by Django 2.2.8 on 2019-12-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20191209_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoopt',
            name='task_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
