# Generated by Django 2.2.8 on 2019-12-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0021_algoopt_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myalgopost',
            name='balanced_dates',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='benchmark',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='initial_capital',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='portfolio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='myalgopost',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
