# Generated by Django 2.2.8 on 2019-12-10 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0023_auto_20191210_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='algoopt',
            name='slug',
            field=models.SlugField(blank=True, max_length=500),
        ),
    ]
